
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-1
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"DeleteEndpointCourseController","number":44,"title":"Delete Course and Course Staff for CourseController","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/44"},{"author":{"id":"MDQ6VXNlcjQyMTYzMjQx","is_bot":false,"login":"jakedel","name":"Jake Delgado"},"headRefName":"jake-deletestaff","number":36,"title":"Implement delete staff from course operation for Courses and tests","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/36"},{"author":{"id":"MDQ6VXNlcjQ0Njg5MjQw","is_bot":false,"login":"Johnsonchan105","name":"Johnson Chan"},"headRefName":"Johnson-#3-F1","number":35,"title":"Added Instructor Column to UserTable and Tests","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/35"}]
