
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-1
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjY5Njk2Njcx","is_bot":false,"login":"Joseph-Foster","name":"Joseph Foster"},"headRefName":"CoursesIndexPage","number":62,"title":"Added Index Page for Courses","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/62"},{"author":{"id":"MDQ6VXNlcjIyNDU0MjE4","is_bot":false,"login":"Dagin-Gregory","name":"Dagin Gregory"},"headRefName":"DG-CoursesIndexPage","number":61,"title":"Dg courses index page","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/61"},{"author":{"id":"MDQ6VXNlcjM2NDk0MTY3","is_bot":false,"login":"ErwanDev","name":"Erwan"},"headRefName":"Erwan-CourseNav","number":60,"title":"Erwan Courses Nav Bar","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/60"},{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"ToggleButtonsUserTable","number":59,"title":"Toggle Buttons for the User Table","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/59"},{"author":{"id":"MDQ6VXNlcjY5Njk2Njcx","is_bot":false,"login":"Joseph-Foster","name":"Joseph Foster"},"headRefName":"JF-CoursesEditPage","number":58,"title":"Edit Page for Courses","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/58"},{"author":{"id":"MDQ6VXNlcjQ0Njg5MjQw","is_bot":false,"login":"Johnsonchan105","name":"Johnson Chan"},"headRefName":"Johnson-#3-B1-#24","number":57,"title":"Ensure Roles Update Correctly using Interceptors","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/57"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-test-ci-cd-pipeline","number":55,"title":"staff - add javadoc comments to ApiController","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/55"}]
