
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-1
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-test-ci-cd-pipeline","number":55,"title":"pc - add javadoc comments to ApiController","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/55"},{"author":{"id":"MDQ6VXNlcjIyNDU0MjE4","is_bot":false,"login":"Dagin-Gregory","name":"Dagin Gregory"},"headRefName":"DG-CoursesTable","number":48,"title":"Added 'Courses' table to frontend and associated tests.","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/48"},{"author":{"id":"MDQ6VXNlcjM2NDk0MTY3","is_bot":false,"login":"ErwanDev","name":"Erwan"},"headRefName":"Erwan-ToggleEndpoints","number":46,"title":"Erwan toggle endpoints","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/46"},{"author":{"id":"MDQ6VXNlcjQyMTYzMjQx","is_bot":false,"login":"jakedel","name":"Jake Delgado"},"headRefName":"jake-deletestaff-instructor","number":45,"title":"Modify DELETE Operation in Courses to work with ROLE_INSTRUCTOR","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/45"},{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"DeleteEndpointCourseController","number":44,"title":"Delete Course and Course Staff for CourseController","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/pull/44"}]
